# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "sorpris"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "Sorpris is a simple theme with custom colors, based on the Base16 theme by Hylke Visser"
homepage = "https://github.com/ador/hugo-sorpris-theme"
tags = ["blog", "syntax highlighting"]
features = ["blog", "syntax highlighting"]
min_version = 0.15

[author]
  name = "Adrienn Szabo"
  homepage = "https://github.com/ador"
